using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureDataLake.DeleteFiles.Definitions;

namespace Frends.AzureDataLake.DeleteFiles;

/// <summary>
/// Azure Data Lake Task.
/// </summary>
public static class AzureDataLake
{
    /// <summary>
    /// Delete files from Azure Data Lake.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureDataLake.DeleteFiles)
    /// </summary>
    /// <param name="input">Input parameters</param>
    /// <param name="options">Options parameters</param>
    /// <param name="token">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool IsSuccess, List&lt;string&gt; DeletedFiles, string ErrorMessage }</returns>
    public static async Task<Result> DeleteFiles(
        [PropertyTab] Input input,
        [PropertyTab] Options options,
        CancellationToken token
    )
    {
        await Task.CompletedTask;
        return new Result();
    }
}
