using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Azure.Identity;
using Azure.Storage.Files.DataLake;
using Azure.Storage.Files.DataLake.Models;
using Frends.AzureDataLake.UploadFiles.Definitions;
using Frends.AzureDataLake.UploadFiles.Exceptions;

namespace Frends.AzureDataLake.UploadFiles;

/// <summary>
/// Azure Data Lake Task.
/// </summary>
public static class AzureDataLake
{
    /// <summary>
    /// Upload files to Azure Data Lake.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureDataLake.UploadFiles)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="options">Optional parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, Dictionary&lt;string, string&gt; Files, ResultError Error }</returns>
    public static async Task<Result> UploadFiles(
        [PropertyTab] Input input,
        [PropertyTab] Connection connection,
        [PropertyTab] Options options,
        CancellationToken cancellationToken
    )
    {
        try
        {
            ValidateParameters(connection, input.ContainerName);

            var container = await GetDataLakeContainer(connection, input.ContainerName, cancellationToken);
            var parallelResults = new ConcurrentDictionary<string, string>();
            var paths = Directory.GetFiles(
                input.SourceDirectory,
                input.FilePattern,
                input.UploadFilesRecursively
                    ? SearchOption.AllDirectories
                    : SearchOption.TopDirectoryOnly
            );

            await Parallel.ForEachAsync(
                paths,
                async (sourcePath, cancellationToken) =>
                    await UploadFile(
                        sourcePath,
                        parallelResults,
                        input,
                        options,
                        container,
                        cancellationToken
                    )
            );

            return new Result(true, new Dictionary<string, string>(parallelResults));
        }
        catch (Exception ex)
        {
            if (options.ThrowErrorOnFailure)
                throw;

            var message = !string.IsNullOrEmpty(options.ErrorMessageOnFailure)
                ? options.ErrorMessageOnFailure
                : ex.Message;
            return new Result(false, new Dictionary<string, string>(), new ResultError(message, ex.Message));
        }
    }

    private static async Task<DataLakeFileSystemClient> GetDataLakeContainer(
        Connection connection,
        string containerName,
        CancellationToken token
    )
    {
        DataLakeServiceClient client = connection.AuthenticationMethod switch
        {
            AuthenticationMethod.ConnectionString => new DataLakeServiceClient(connection.ConnectionString),
            AuthenticationMethod.OAuth2
                => new DataLakeServiceClient(
                    new Uri($"https://{connection.StorageAccountName}.dfs.core.windows.net"),
                    new ClientSecretCredential(
                        connection.TenantId,
                        connection.ApplicationId,
                        connection.ClientSecret,
                        new ClientSecretCredentialOptions()
                    )
                ),
            _ => throw new InvalidEnumArgumentException(),
        };

        var container = client.GetFileSystemClient(containerName);

        if (!await container.ExistsAsync(token))
            throw new ContainerNotFoundException(containerName);
        return container;
    }

    private static void ValidateParameters(Connection connection, string containerName)
    {
        if (
            connection.AuthenticationMethod is AuthenticationMethod.OAuth2
            && (
                connection.ApplicationId is null
                || connection.ClientSecret is null
                || connection.TenantId is null
                || connection.StorageAccountName is null
            )
        )
            throw new InvalidInputException(
                "Connection.StorageAccountName, Connection.ClientSecret, Connection.ApplicationId and Connection.TenantId parameters can't be empty when Connection.AuthenticationMethod = OAuth2."
            );
        if (
            connection.AuthenticationMethod is AuthenticationMethod.ConnectionString
            && string.IsNullOrWhiteSpace(connection.ConnectionString)
        )
            throw new InvalidInputException(
                "Connection.ConnectionString parameter can't be empty when Connection.AuthenticationMethod = ConnectionString."
            );
        if (string.IsNullOrWhiteSpace(containerName))
            throw new InvalidInputException("Input.ContainerName parameter can't be empty.");
    }

    private static async Task UploadFile(
        string srcPath,
        ConcurrentDictionary<string, string> parallelResults,
        Input input,
        Options options,
        DataLakeFileSystemClient container,
        CancellationToken token
    )
    {
        var relativePath = srcPath[input.SourceDirectory.Length..]
            .TrimStart(Path.DirectorySeparatorChar);

        var destinationPath = input.TargetDirectory is null
            ? relativePath
            : Path.Combine(input.TargetDirectory, relativePath);

        if (container.GetFileClient(destinationPath).Exists(token) && input.ActionOnExistingFile != HandleExistingFile.Overwrite)
        {
            if (options.ThrowErrorOnFailure)
                throw new FileAlreadyExistsException(destinationPath);
            return;
        }

        DataLakeFileClient fileClient = await container.CreateFileAsync(
            destinationPath,
            null,
            token
        );

        if (new FileInfo(srcPath).Length > 0)
        {
            DataLakeFileUploadOptions uploadOptions = new DataLakeFileUploadOptions
            {
                Close = input.Close
            };

            await fileClient.UploadAsync(srcPath, uploadOptions, token);
        }

        parallelResults.TryAdd(srcPath, fileClient.Uri.AbsoluteUri);
    }
}
