using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureDataLake.UploadFiles.Definitions;

namespace Frends.AzureDataLake.UploadFiles;

/// <summary>
/// Azure Data Lake Task.
/// </summary>
public class AzureDataLake
{
    /// <summary>
    /// Upload files to Azure Data Lake.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureDataLake.UploadFiles)
    /// </summary>
    /// <param name="source">Source parameters.</param>
    /// <param name="destination">Destination parameters.</param>
    /// <param name="options">Optional parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this Task.</param>
    /// <returns>Object { bool Success, Dictionary&lt;string, string&gt; Data }</returns>
    public static async Task<Result> UploadFiles(
        [PropertyTab] SourceFilter source,
        [PropertyTab] DesignerTransaction destination,
        [PropertyTab] Options options,
        CancellationToken cancellationToken
    )
    {
        await Task.CompletedTask;
        return new Result(true, new Dictionary<string, string>());
    }
}
