using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using Frends.AzureDataLake.DownloadFiles.Definitions;

namespace Frends.AzureDataLake.DownloadFiles;

/// <summary>
/// Azure Data Lake Task.
/// </summary>
public static class AzureDataLake
{
    /// <summary>
    /// Downloads files from Azure Data Lake.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureDataLake.DownloadFiles)
    /// </summary>
    /// <param name="source">Source parameters.</param>
    /// <param name="destination">Destination parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="token">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool IsSuccess, Dictionary&lt;string, string&gt; DownladedFiles, string ErrorMessage }</returns>
    public static async Task<Result> DownloadFiles(
        [PropertyTab] Source source,
        [PropertyTab] Destination destination,
        [PropertyTab] Options options,
        CancellationToken token
    )
    {
        await Task.CompletedTask;
        return new Result();
    }
}
