using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Azure.Identity;
using Azure.Storage.Files.DataLake;
using Frends.AzureDataLake.DownloadFiles.Definitions;
using Frends.AzureDataLake.DownloadFiles.Exceptions;
using Frends.AzureDataLake.DownloadFiles.Helpers;
using Microsoft.Extensions.FileSystemGlobbing;
using static Frends.AzureDataLake.DownloadFiles.Definitions.Constants;

namespace Frends.AzureDataLake.DownloadFiles;

/// <summary>
/// Azure Data Lake Task.
/// </summary>
public static class AzureDataLake
{
    /// <summary>
    /// Downloads files from Azure Data Lake.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.AzureDataLake.DownloadFiles)
    /// </summary>
    /// <param name="input">Input parameters.</param>
    /// <param name="connection">Connection parameters.</param>
    /// <param name="options">Options parameters.</param>
    /// <param name="cancellationToken">Token generated by Frends to stop this task.</param>
    /// <returns>Object { bool Success, Dictionary&lt;string, string&gt; DownladedFiles, Error Error }</returns>
    public static async Task<Result> DownloadFiles(
        [PropertyTab] Input input,
        [PropertyTab] Connection connection,
        [PropertyTab] Options options,
        CancellationToken cancellationToken
    )
    {
        try
        {
            ValidateConnectionParameters(connection);
            ValidateInputParameters(input);

            var container = await GetDataLakeContainer(input, cancellationToken);
            var paralelResults = new ConcurrentDictionary<string, string>();
            var allSrcFiles = container
                .GetPaths("/", true, false, cancellationToken: cancellationToken)
                .Where(x => (bool)!x.IsDirectory)
                .Select(x => x.Name);
            var matches = new Matcher().AddInclude($"**/{input.FilePattern}").Match(allSrcFiles);

            await Parallel.ForEachAsync(
                matches.Files,
                async (match, token) =>
                {
                    var (srcFilePath, dstFilePath) = await DownloadFile(
                        match.Path,
                        connection,
                        container,
                        token
                    );
                    paralelResults.TryAdd(srcFilePath, dstFilePath);
                }
            );

            return new Result
            {
                Success = true,
                DownladedFiles = new Dictionary<string, string>(paralelResults)
            };
        }
        catch (Exception ex)
        {
            return ex.Handle(options);
        }
    }

    private static void ValidateConnectionParameters(Connection connection)
    {
        if (!Directory.Exists(connection.Directory))
            throw new InvalidInputException("Provided destintation directory doesn't exists");
    }

    private static void ValidateInputParameters(Input input)
    {
        if (
            input.ConnectionMethod is ConnectionMethod.OAuth2
            && (
                input.ApplicationID is null
                || input.ClientSecret is null
                || input.TenantID is null
                || input.StorageAccountName is null
            )
        )
            throw new InvalidInputException(
                "Input.StorageAccountName, Input.ClientSecret, Input.ApplicationID and Input.TenantID parameters can't be empty when Input.ConnectionMethod = OAuth."
            );
        if (
            input.ConnectionMethod is ConnectionMethod.ConnectionString
            && string.IsNullOrWhiteSpace(input.ConnectionString)
        )
            throw new InvalidInputException(
                "ConnectionString parameter can't be empty when Input.ConnectionMethod = ConnectionString."
            );
        if (string.IsNullOrWhiteSpace(input.ContainerName))
            throw new InvalidInputException("ContainerName parameter can't be empty.");
        if (input.ContainerName.Any(char.IsUpper))
            throw new InvalidInputException("ContainerName can't contain upper letters.");
    }

    private static async Task<DataLakeFileSystemClient> GetDataLakeContainer(
        Input input,
        CancellationToken token
    )
    {
        DataLakeServiceClient client = input.ConnectionMethod switch
        {
            ConnectionMethod.ConnectionString => new DataLakeServiceClient(input.ConnectionString),
            ConnectionMethod.OAuth2
                => new DataLakeServiceClient(
                    new Uri($"https://{input.StorageAccountName}.blob.core.windows.net"),
                    new ClientSecretCredential(
                        input.TenantID,
                        input.ApplicationID,
                        input.ClientSecret,
                        new ClientSecretCredentialOptions()
                    )
                ),
            _ => throw new InvalidEnumArgumentException(),
        };

        var container = client.GetFileSystemClient(input.ContainerName);

        if (!await container.ExistsAsync(token))
            throw new ContainerNotFoundException(input.ContainerName);

        return container;
    }

    private static async Task<(string srcFilePath, string dstFilePath)> DownloadFile(
        string sourcePath,
        Connection connection,
        DataLakeFileSystemClient container,
        CancellationToken token
    )
    {
        var fileClient = container.GetFileClient(sourcePath);
        var destinationPath = Path.Combine(connection.Directory, sourcePath);

        if (!connection.Overwrite && File.Exists(destinationPath))
            return (fileClient.Uri.AbsoluteUri, "File already exists");
        Directory.CreateDirectory(Directory.GetParent(destinationPath).FullName);
        using FileStream downloadStream = File.Create(destinationPath);
        await fileClient.ReadToAsync(downloadStream, cancellationToken: token);

        return (fileClient.Uri.AbsoluteUri, destinationPath);
    }
}
