name: CreateContainer_build_main

on:
  push:
    branches:
      - main
    paths:
      - "Frends.AzureDataLake.CreateContainer/**"
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.AzureDataLake.CreateContainer
      env_var_name_1: Frends_AzureDataLake_ConnString
      env_var_name_2: Frends_AzureDataLake_AppID
      env_var_name_3: Frends_AzureDataLake_TenantID
      env_var_name_4: Frends_AzureDataLake_ClientSecret
      env_var_name_5: Frends_AzureDataLake_StorageAccount
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_AZUREDATALAKE_CONNSTRING }}
      env_var_value_2: ${{ secrets.FRENDS_AZUREDATALAKE_APPID }}
      env_var_value_3: ${{ secrets.FRENDS_AZUREDATALAKE_TENANTID }}
      env_var_value_4: ${{ secrets.FRENDS_AZUREDATALAKE_CLIENTSECRET }}
      env_var_value_5: ${{ secrets.FRENDS_AZUREDATALAKE_STORAGEACCOUNT }}
