name: DeleteContainer_build_main

on:
  push:
    branches:
      - main
    paths:
      - "Frends.AzureDataLake.DeleteContainer/**"
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.AzureDataLake.DeleteContainer
      env_var_name_1: FRENDS_AZUREDATALAKE_CONNSTRING
      env_var_name_2: FRENDS_AZUREDATALAKE_APPID
      env_var_name_3: FRENDS_AZUREDATALAKE_CLIENTSECRET
      env_var_name_4: FRENDS_AZUREDATALAKE_TENANTID
      env_var_name_5: FRENDS_AZUREDATALAKE_STORAGEACCOUNT
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.FRENDS_AZUREDATALAKE_CONNSTRING }}
      env_var_value_2: ${{ secrets.FRENDS_AZUREDATALAKE_APPID }}
      env_var_value_3: ${{ secrets.FRENDS_AZUREDATALAKE_CLIENTSECRET }}
      env_var_value_4: ${{ secrets.FRENDS_AZUREDATALAKE_TENANTID }}
      env_var_value_5: ${{ secrets.FRENDS_AZUREDATALAKE_STORAGEACCOUNT }}
